### ISSUE TITLE
Documentation is not complete

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_setup_assistant#1]
On http://moveit.ros.org/setup_assistant.html , the documentation is not completed.

Some critical sections, such as 'end effectors' are currently missing and make using MoveIT difficult.

**Comment by davetcoleman** [comment]
This is on my to-do list, I'll move it to high priority!

**Comment by davetcoleman** [comment]
Finished documenting the Setup Assistant, its been pushed to moveit-docs on github but Ioan or someone needs to push it to the live server.
