### ISSUE TITLE
Failed to generate package.xml

### ISSUE THREAD

**Issue by leameow** [moveit/moveit_setup_assistant#10]
Hi,
following the MoveIt! Setup Assistant tutorial, I get an error when I try to generate the package. An error box is displayed with the message: Failed to generate file /path/to/dir/package.xml.

In the console, I get the following message:

[ERROR] [1356903269.751470929]: Unable to find template file /opt/ros/groovy/share/moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.disabled

Looking in the folder template folder, I see only: CMakeLists.txt,  launch and  package.xml.template.

I am using ros groovy from repo on ubuntu 12.04.

Thanks

**Comment by davetcoleman** [comment]
I just checked and it looks like that file was renamed in both the [template directory](https://github.com/ros-planning/moveit_setup_assistant/tree/groovy-devel/templates/moveit_config_pkg_template) and the [source code](https://github.com/ros-planning/moveit_setup_assistant/blob/groovy-devel/src/widgets/configuration_files_widget.cpp) to the ".template" suffix, from the original ".disabled" suffix. Are you sure you have the latest version of both? I'm not at my ROS setup computer so cannot test today. Maybe the debian is out of date.

**Comment by davetcoleman** [comment]
Are you running from source or debian? If from source, a temp fix is to rename moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.template to 
moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.disabled

**Comment by leameow** [comment]
I'm running from debian (ros-groovy-moveit-setup-assistant's version: 0.3.1-0precise-20121225-0617-+0000)
I ran a upgrade and a dist-upgrade and there is nothing to update.
I renamed it to *.disabled and it works just fine.

**Comment by isucan** [comment]
I'll push a new release today and things should become fine then. Thanks for reporting!
