### ISSUE TITLE
Jade release?

### ISSUE THREAD

**Issue by gavanderhoorn** [moveit/moveit_setup_assistant#106]
Just wondering if it would be possible to do a release of `moveit_setup_assistant` into Indigo/Jade to get everything [past 0.6.0](https://github.com/ros-planning/moveit_setup_assistant/compare/0.6.0...indigo-devel) released?
#102 keeps biting me on machines that don't have the assistant from-source.

**Comment by gavanderhoorn** [comment]
Friendly ping?

(reminded by ROS Answers: [MoveIt Setup Assistant ROS Jade](http://answers.ros.org/question/217049/moveit-setup-assistant-ros-jade/))

**Comment by gavanderhoorn** [comment]
Fixed with 8da76a5f.

**Comment by alextoind** [comment]
@gavanderhoorn actually the fix is only for Indigo. By compiling the source it works pretty fine in Jade, but it would be cleaner if `ros-jade-moveit-setup-assistant` is released.

**Comment by gavanderhoorn** [comment]
You're right @alextoind: I've changed the title of the issue and reopened it.

**Comment by 130s** [comment]
Working on this, finally.

**Comment by gavanderhoorn** [comment]
Much appreciated, thanks :tada:

**Comment by 130s** [comment]
I'll wait at least for https://github.com/ros-planning/moveit_setup_assistant/issues/110 (that has a PR to) to be resolved.

**Comment by davetcoleman** [comment]
I don't think you need to wait for #110 - it's not a critical bug, just a suggested new feature. The behavior hasn't really been an issue for the ~5 years since I wrote the Setup Assistant, but of course it would be a nice improvement when its ready.

**Comment by 130s** [comment]
Oh, kay. Making a Jade release now.

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/11975
