### ISSUE TITLE
Joints don't highlight when selecting multiple / using arrow keys to select

### ISSUE THREAD

**Issue by dgossow** [moveit/moveit_setup_assistant#14]
In the Add Joints section of Planning Groups, when you select a link in the left pane, it highlights in the robot view.
This doesn't work however when you select multiple links, or when you navigate around in the link list using the up/down arrow keys on your keyboard.

**Comment by davetcoleman** [comment]
This was not an easy feature addition, but its done.
https://github.com/ros-planning/moveit_setup_assistant/commit/bbacbc570aaa2956827faa9ce46903676c9a0cdd
