### ISSUE TITLE
unclear warnings

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_setup_assistant#17]
When setup assistant is used and virtual joints are added, such warnings appear:

```
[ WARN] [1358460402.029178460]: No joint matching multi-dof joint
'virtual_joint'
[ WARN] [1358460402.061020743]: No joint matching multi-dof joint
'virtual_joint'
```

**Comment by davetcoleman** [comment]
I remember this issue too, but it seems to have gone away. I can't reproduce it right now.

**Comment by davetcoleman** [comment]
I do get the warning

```
 INFO ros.rosconsole_bridge.console_bridge: No root joint specified. Assuming fixed joint
```

When I create a planning group w/the PR2 with the joints "fr_caster_rotation_joint" and "fl_caster_l_wheel_joint". But that warning is not coming from the Setup Assistant but rather ros_core. The warning you mentioned is also not coming directly from the SA.
