### ISSUE TITLE
Simplify addition of planning groups

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_setup_assistant#18]
Having too many buttons for adding groups may be confusing. If adding joints will be the usual way to add a group, we should offer that as a default option with the other options offered as advanced options that open up only if the user asks for them.

**Comment by davetcoleman** [comment]
Would a kinematic chain be a better default option? I don't want to spend too much time on this issue but a new screenshot is attached. I'll consider this closed but feel free to re-open.

![Screenshot from 2013-03-23 13:24:05](https://f.cloud.github.com/assets/561060/294554/a0781ae4-93f7-11e2-85a2-89fe4757b990.png)
