### ISSUE TITLE
moveit_setup_assistant crashes when loading urdf

### ISSUE THREAD

**Issue by arismendi** [moveit/moveit_setup_assistant#21]
I am following the Quick Start guide and when I press the load files button it gets to 60% and then crashes

[ INFO] [1361473044.186998322]: Setting Param Server with Robot Description
[ERROR] [1361473044.190120362]: [setParam] Failed to contact master at [localhost:11311].  Retrying...
[ INFO] [1361473044.278316418]: Connected to master at [localhost:11311]
[ INFO] [1361473044.283905399]: Robot semantic model successfully loaded.
[ INFO] [1361473044.284051577]: Setting Param Server with Robot Semantic Description
[ INFO] [1361473044.333059269]: No root joint specified. Assuming fixed joint
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
REQUIRED process [moveit_setup_assistant-2] has died!
process has died [pid 1991, exit code -4, cmd /opt/ros/groovy/lib/moveit_setup_assistant/moveit_setup_assistant __name:=moveit_setup_assistant __log:=/home/cesar/.ros/log/7e46ed80-7c58-11e2-956c-001fc6be20b5/moveit_setup_assistant-2.log].
log file: /home/cesar/.ros/log/7e46ed80-7c58-11e2-956c-001fc6be20b5/moveit_setup_assistant-2*.log
Initiating shutdown! 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[moveit_setup_assistant-2] killing on exit

**Comment by isucan** [comment]
Can you tell me a little more about the machine you are using?
You are running from the .deb installation, correct?
What URDF file are you loading?

**Comment by davetcoleman** [comment]
This looks like a problem some of my students are having who's CPU's don't support the fancy CPU instructions FCL requires. 

Try:
roslaunch moveit_setup_assistant setup_assistant debug:=true
And when it segfaults type "bt" and post the backtrace

**Comment by davetcoleman** [comment]
Arismendi, do you ever figure out this issue? Still problems? I plan on closing this Issue otherwise.

**Comment by arismendi** [comment]
I just try again a moment ago and it worked. So maybe an update or so. I am sorry for the late reply.

**Comment by drohr5D** [comment]
Hi, I've run into the same problem. Please find the backtrace below. David

#0  0xb5f62107 in shapes::(anonymous namespace)::extractMeshData(aiScene const_, aiNode const_, aiMatrix4x4t<float> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::aligned_allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >&, std::vector<unsigned int, std::allocator<unsigned int> >&) [clone .constprop.206]() from /media/5D/bin/ros/moveit/devel/lib/libgeometric_shapes.so
#1  0xb5f6242b in shapes::createMeshFromAsset(aiScene const_, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, std::string const&) () from /media/5D/bin/ros/moveit/devel/lib/libgeometric_shapes.so
#2  0xb5f627ad in shapes::createMeshFromBinary(char const_, unsigned int, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, std::string const&) () from /media/5D/bin/ros/moveit/devel/lib/libgeometric_shapes.so
#3  0xb5f62a34 in shapes::createMeshFromResource(std::string const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&) () from /media/5D/bin/ros/moveit/devel/lib/libgeometric_shapes.so
#4  0xb6bb4661 in robot_model::RobotModel::constructShape(urdf::Geometry const_) () from /media/5D/bin/ros/moveit/devel/lib/libmoveit_robot_model.so
#5  0xb6bb5e96 in robot_model::RobotModel::constructLinkModel(urdf::Link const_, std::map<urdf::Link const*, std::pair<urdf::Link const*, urdf::Joint const*>, std::less<urdf::Link const*>, std::allocator<std::pair<urdf::Link const* const, std::pair<urdf::Link const*, urdf::Joint const*> > > > const&) () from /media/5D/bin/ros/moveit/devel/lib/libmoveit_robot_model.so
#6  0xb6bb8df7 in robot_model::RobotModel::buildRecursive(robot_model::LinkModel_, urdf::Link const_, std::map<urdf::Link const*, std::pair<urdf::Link const*, urdf::Joint const*>, std::less<urdf::Link const*>, std::allocator<std::pair<urdf::Link const* const, std::pair<urdf::Link const*, urdf::Joint const*> > > > const&, std::map<urdf::Link const*, std::vector<urdf::Link const*, std::allocator<urdf::Link const*> >, std::less<urdf::Link const*>, std::allocator<std::pair<urdf::Link const* const, std::vector<urdf::Link const*, std::allocator<urdf::Link const*> > > > > const&, srdf::Model const&) () from /media/5D/bin/ros/moveit/devel/lib/libmoveit_robot_model.so
#7  0xb6bb8fab in robot_model::RobotModel::buildRecursive(robot_model::LinkModel_, urdf::Link const_, std::map<urdf::Link const*, std::pair<urdf::Link const*, urdf::Joint const*>, std::less<urdf::Link const*>, std::allocator<std::pair<urdf::Link const* const, std::pair<urdf::Link const*, urdf::Joint const*> > > > const&, std::map<urdf::Link const*, std::vector<urdf::Link const*, std::allocator<urdf::Link const*> >, std::less<urdf::Link const*>, std::allocator<std::pair<urdf::Link const* const, std::vector<urdf::Link const*, std::allocator<urdf::Link const*> > > > > const&, srdf::Model const&) () from /media/5D/bin/ros/moveit/devel/lib/libmoveit_robot_model.so
#8  0xb6bbd271 in robot_model::RobotModel::buildModel(boost::shared_ptr<urdf::ModelInterface const> const&, boost::shared_ptr<srdf::Model const> const&, std::string const&) ()
   from /media/5D/bin/ros/moveit/devel/lib/libmoveit_robot_model.so
#9  0xb6bbdeb0 in robot_model::RobotModel::RobotModel(boost::shared_ptr<urdf::ModelInterface const> const&, boost::shared_ptr<srdf::Model const> const&) () from /media/5D/bin/ros/moveit/devel/lib/libmoveit_robot_model.so
#10 0xb6cd2f4d in moveit_setup_assistant::MoveItConfigData::getRobotModel() () from /media/5D/bin/ros/moveit/devel/lib/libmoveit_setup_assistant_tools.so
#11 0xb6cd8c00 in moveit_setup_assistant::MoveItConfigData::getPlanningScene() () from /media/5D/bin/ros/moveit/devel/lib/libmoveit_setup_assistant_tools.so
#12 0xb7f9820a in moveit_setup_assistant::RobotPosesWidget::RobotPosesWidget(QWidget_, boost::shared_ptr<moveit_setup_assistant::MoveItConfigData>) () from /media/5D/bin/ros/moveit/devel/lib/libmoveit_setup_assistant_widgets.so
#13 0xb7fbaa79 in moveit_setup_assistant::SetupAssistantWidget::progressPastStartScreen() () from /media/5D/bin/ros/moveit/devel/lib/libmoveit_setup_assistant_widgets.so
#14 0x0805d140 in moveit_setup_assistant::SetupAssistantWidget::qt_static_metacall(QObject_, QMetaObject::Call, int, void**) [clone .part.15]()
#15 0xb72f66b1 in QMetaObject::activate(QObject_, QMetaObject const_, int, void**) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#16 0x0805d537 in moveit_setup_assistant::StartScreenWidget::readyToProgress() ()
#17 0xb7f6a3f7 in moveit_setup_assistant::StartScreenWidget::loadNewFiles() () from /media/5D/bin/ros/moveit/devel/lib/libmoveit_setup_assistant_widgets.so
#18 0xb7f6c701 in moveit_setup_assistant::StartScreenWidget::loadFilesClick() () from /media/5D/bin/ros/moveit/devel/lib/libmoveit_setup_assistant_widgets.so
#19 0xb72f66b1 in QMetaObject::activate(QObject_, QMetaObject const_, int, void**) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#20 0xb7cb397d in QAbstractButton::clicked(bool) () from /usr/lib/i386-linux-gnu/libQtGui.so.4

**Comment by drohr5D** [comment]
Slight more after that:
#21 0xb79a762d in ?? () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#22 0xb79a8c9b in ?? () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#23 0xb79a8f56 in QAbstractButton::mouseReleaseEvent(QMouseEvent_) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#24 0xb75d61ac in QWidget::event(QEvent_) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#25 0xb79a81f9 in QAbstractButton::event(QEvent_) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#26 0xb7a4b768 in QPushButton::event(QEvent_) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#27 0xb757bed4 in QApplicationPrivate::notify_helper(QObject_, QEvent_) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#28 0xb7582024 in QApplication::notify(QObject_, QEvent_) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#29 0xb72df97e in QCoreApplication::notifyInternal(QObject_, QEvent_) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#30 0xb757ce95 in QApplicationPrivate::sendMouseEvent(QWidget_, QMouseEvent_, QWidget_, QWidget_, QWidget*_, QPointer<QWidget>&, bool) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#31 0xb7609074 in ?? () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#32 0xb7607c0d in QApplication::x11ProcessEvent(_XEvent_) () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#33 0xb7634eac in ?? () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#34 0xb67ded86 in g_main_context_dispatch () from /lib/i386-linux-gnu/libglib-2.0.so.0
#35 0xb67df125 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#36 0xb67df201 in g_main_context_iteration () from /lib/i386-linux-gnu/libglib-2.0.so.0
#37 0xb7312887 in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#38 0xb7634aaa in ?? () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#39 0xb72de50d in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#40 0xb72de7a9 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#41 0xb72e3eba in QCoreApplication::exec() () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#42 0xb7579a74 in QApplication::exec() () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#43 0x08058a72 in main ()

**Comment by isucan** [comment]
does this happen every time with this urdf? if so, can you send me the urdf
and the meshes you have?

**Comment by drohr5D** [comment]
Hi isucan,

Yes, it happens every time. I am using the PR2 urdf as generated by the 
following:

rosrun xacro xacro.py 
/opt/ros/groovy/stacks/pr2_common/pr2_description/robots/pr2.urdf.xacro 

> pr2.urdf

Please find the file attached

Best,
David

**Comment by drohr5D** [comment]
In case people on the e-mail list can't receive attachments through git here is the urdf:

https://gist.github.com/drohr5D/5551267

**Comment by drohr5D** [comment]
As with the person before me, this problem has disappeared with restart. Thank you for your help. David

**Comment by Chris177** [comment]
I was getting a similar error, apparently this error is due GLX is not properly set up for  3D accelerated OpenGL.  So a solution that could explain why it's working now is you had your video driver updated or you changed it.
