### ISSUE TITLE
Default ompl_planning.yaml settings

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_setup_assistant#22]
In order to get MoveIt benchmarking to work correctly with OMPL, the following two lines are needed in `ompl_planning.yaml`

```
 projection_evaluator: joints(shoulder_pan_joint,shoulder_pitch_joint)
 longest_valid_segment_fraction: 0.05
```

Where the two joints are suggested to be the first two joints in the kinematic chain. This should probably be added by default in the MoveIt Setup Assistant. Thoughts?

See [OMPL Benchmarking](http://moveit.ros.org/wiki/index.php/Groovy/Benchmarking/Motion_Planning#OMPL_Example) for more info

**Comment by isucan** [comment]
I agree

**Comment by davetcoleman** [comment]
Implemented https://github.com/ros-planning/moveit_setup_assistant/commit/e2d4442c307b3d1b85da93c5f2eb4e69104a949d

I added a function `decideProjectionJoints` in `moveit_config_data.cpp` that simply takes the first two joints in a joint model group and uses them as the projection evaluation joints. Let me know if you have a better heuristic.
