### ISSUE TITLE
robot_description dependency

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_setup_assistant#28]
add dependency to generated packages to the urdf package it came from (if there is one)

**Comment by davetcoleman** [comment]
@isucan, is this ok? i'm thinking in package.xml have something like:

```
<run_depend>pr2_description</run_depend>
```

if the MoveIt config pkg was created with a URDF inside a ros package (not absolute path)

**Comment by isucan** [comment]
That sounds good. Add a build dependency as well.

**Comment by davetcoleman** [comment]
Done https://github.com/ros-planning/moveit_setup_assistant/commit/87ec20e55549d3ccfa10d46bdf8065ab01e07448
