### ISSUE TITLE
Gtk-WARNING

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_setup_assistant#29]
When typing in the name of a package to be generated on the last screen, using the popup, I get the warning:
(moveit_setup_assistant:18319): Gtk-WARNING **: Unable to find default local directory monitor type

**Comment by davetcoleman** [comment]
Researching Google, it looks like a complicated system dependency issue and there are no easy solutions. I'm not sure it worth trying to fix since its just a warning.

**Comment by isucan** [comment]
I agree. We should not fix this.
