### ISSUE TITLE
Setup Assistant does not generate sensor_manager launch file

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_setup_assistant#3]
In the robot_name_moveit_generated package, the move_group.launch file has the following include:

This file is not generated and can cause issues if trying to use the move_group.launch file.

**Comment by isucan** [comment]
I think there was a paste error. Which file is that?

**Comment by chadrockey** [comment]
include ns="move_group" file="$(find arm_moveit_generated)/launch/sensor_manager.launch">
    arg name="moveit_sensor_manager" value="breadboard_arm_description"
  </include

**Comment by chadrockey** [comment]
Looks like it ate my XML, it's __arm_moveit_generated/launch/sensor_manager.launch.

**Comment by isucan** [comment]
Will fix asap.
