### ISSUE TITLE
crash when loading URDF with alpha debs

### ISSUE THREAD

**Issue by acornacorn** [moveit/moveit_setup_assistant#36]
When using the alpha debs I see a crash in setup assistant when loading the pr2 URDF.

following steps here: http://moveit.ros.org/wiki/index.php/Groovy/PR2/Setup_Assistant/Quick_Start#STEP_1:_Start

repro:
rosrun xacro xacro.py /opt/ros/groovy/stacks/pr2_common/pr2_description/robots/pr2.urdf.xacro > pr2.urdf
run roslaunch moveit_setup_assistant setup_assistant.launch
select the pr2.urdf
click 'load files'
crashes.

When running with debug:=true I get the following stack when it segfaults:
#0  0x00007fffec984415 in Ogre::EdgeListBuilder::buildTrianglesEdges(Ogre::EdgeListBuilder::Geometry const&) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.7.4
#1  0x00007fffec984bff in Ogre::EdgeListBuilder::build() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.7.4
#2  0x00007fffeca2f9ee in Ogre::Mesh::buildEdgeList() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.7.4
#3  0x00007ffff35abac1 in ogre_tools::STLLoader::toMesh(std::string const&) () from /opt/ros/groovy/lib/librviz.so
#4  0x00007ffff3592236 in rviz::loadMeshFromResource(std::string const&) () from /opt/ros/groovy/lib/librviz.so
#5  0x00007ffff35c9f9e in rviz::RobotLink::createEntityForGeometryElement(boost::shared_ptr<urdf::Link const> const&, urdf::Geometry const&, urdf::Pose const&, Ogre::SceneNode_, Ogre::Entity_&, Ogre::SceneNode_&, Ogre::SceneNode_&) () from /opt/ros/groovy/lib/librviz.so
#6  0x00007ffff35ca7de in rviz::RobotLink::createVisual(boost::shared_ptr<urdf::Link const> const&) () from /opt/ros/groovy/lib/librviz.so
#7  0x00007ffff35ca993 in rviz::RobotLink::load(urdf::ModelInterface const&, boost::shared_ptr<urdf::Link const> const&, bool, bool) () from /opt/ros/groovy/lib/librviz.so
#8  0x00007ffff35cb99f in rviz::Robot::load(urdf::ModelInterface const&, bool, bool) () from /opt/ros/groovy/lib/librviz.so
#9  0x00007fffeda1b61f in moveit_rviz_plugin::RobotStateVisualization::load(urdf::ModelInterface const&, bool, bool) () from /opt/ros/groovy/lib/libmoveit_rviz_plugin_render_tools.so
#10 0x00007ffff38947af in moveit_rviz_plugin::RobotStateDisplay::loadRobotModel(std::string const&) () from /opt/ros/groovy/lib/libmoveit_robot_state_rviz_plugin_core.so
#11 0x00007ffff3894e77 in moveit_rviz_plugin::RobotStateDisplay::onEnable() () from /opt/ros/groovy/lib/libmoveit_robot_state_rviz_plugin_core.so
#12 0x00007ffff355564b in rviz::Display::onEnableChanged() () from /opt/ros/groovy/lib/librviz.so
#13 0x00007ffff36125a9 in ?? () from /opt/ros/groovy/lib/librviz.so
#14 0x00007ffff6b27281 in QMetaObject::activate(QObject_, QMetaObject const_, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#15 0x00007ffff35ba141 in rviz::Property::setValue(QVariant const&) () from /opt/ros/groovy/lib/librviz.so
#16 0x00007ffff35550de in rviz::Display::setEnabled(bool) () from /opt/ros/groovy/lib/librviz.so
#17 0x00007ffff7bb7a4d in moveit_setup_assistant::SetupAssistantWidget::loadRviz() () from /opt/ros/groovy/lib/libmoveit_setup_assistant_widgets.so
#18 0x00007ffff6b27281 in QMetaObject::activate(QObject_, QMetaObject const_, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#19 0x00007ffff7b6f12c in moveit_setup_assistant::StartScreenWidget::loadNewFiles() () from /opt/ros/groovy/lib/libmoveit_setup_assistant_widgets.so
#20 0x00007ffff7b70fc9 in moveit_setup_assistant::StartScreenWidget::loadFilesClick() () from /opt/ros/groovy/lib/libmoveit_setup_assistant_widgets.so
#21 0x00007ffff6b27281 in QMetaObject::activate(QObject_, QMetaObject const_, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#22 0x00007ffff76c5c72 in QAbstractButton::clicked(bool) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#23 0x00007ffff7403a4e in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#24 0x00007ffff7404d8b in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#25 0x00007ffff7404ffc in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#26 0x00007ffff7086144 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#27 0x00007ffff7035894 in QApplicationPrivate::notify_helper(QObject_, QEvent_) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#28 0x00007ffff703b0bf in QApplication::notify(QObject_, QEvent_) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#29 0x00007ffff6b12e9c in QCoreApplication::notifyInternal(QObject_, QEvent_) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#30 0x00007ffff7036862 in QApplicationPrivate::sendMouseEvent(QWidget_, QMouseEvent_, QWidget_, QWidget_, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#31 0x00007ffff70b5bf5 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#32 0x00007ffff70b4bae in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#33 0x00007ffff70de0d2 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#34 0x00007ffff2aa4d53 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff2aa50a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff2aa5164 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff6b423bf in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#38 0x00007ffff70ddd5e in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#39 0x00007ffff6b11c82 in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#40 0x00007ffff6b11ed7 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#41 0x00007ffff6b16f67 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#42 0x0000000000413788 in main ()

**Comment by isucan** [comment]
the build farm is swamped. the new deb is not actually built yet. you are probably running with an old deb agains some newer debs and there are ABI differences
