### ISSUE TITLE
Invalid planning_context.launch generated for XACRO input

### ISSUE THREAD

**Issue by JeremyZoss** [moveit/moveit_setup_assistant#39]
The Setup Assistant now supports setting the input URDF configuration using an XACRO macro directly rather than converting to URDF first.  This input path is translated almost directly into planning_context.launch, to load the URDF data into the robot_description parameter.

If an XACRO file is used as input to the SA, the planning_context.launch file loads the xacro data (rather than URDF data) to the robot_description parameter.  Running demo.launch fails in this case.

The SA templates should be expanded to process the input data differently for XACRO or URDF, prior to loading the data into the robot_description parameter.

**Comment by JeremyZoss** [comment]
Actually, I think this commit (3a8cf10) addresses Issue #38, not #39.

**Comment by isucan** [comment]
you are right :)
