### ISSUE TITLE
Setup Assistant Crashes with an Assertion Failure

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_setup_assistant#4]
"setup_assistant: 
moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp:341: void moveit_setup_assistant::SetupAssistantWidget::highlightGroup(const string&): Assertion `joint_model_group' failed.
Aborted (core dumped)"

Steps to Reproduce:
1.) Create New MoveIT Configuration Package
2.) Add arm urdf
3.) Go through self collsions
4.) Add 'arm' planning group.  Add LINKS instead of joints to group 'arm'.
5.) Save group.
6.) Edit arm/links to remove all links.
7.) Edit arm/joints.
8.) Assertion failure.

**Comment by isucan** [comment]
fixed in fuerte-devel d8e944a
