### ISSUE TITLE
Empty Planning Group Crash

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_setup_assistant#5]
Creating a new planning group, then selecting to add subgroups, then pressing cancel can cause instability and crashing in the application. Unable to fix at the moment due to old repo setup.

**Comment by isucan** [comment]
Hey Dave, I don't understand what you mean by old repo setup. Are you using the github repo?

**Comment by davetcoleman** [comment]
My repos are still the mercurial ones. I tried installing the git version for Fuerte, but ran into some errors and think I should just wait to switch to Groovy. Not sure, working on documentation atm.

**Comment by isucan** [comment]
I see. Well I fixed a number of bugs in the setup assistant already, including ones that have to do with empty subgroups. You can use git without using groovy. Just use those git repos. I also added a button, changed some messages slightly, so for docs, use the latest version if possible. I should have deleted the mercurial repos. I will do that today.

**Comment by isucan** [comment]
I believe this was fixed with #4

**Comment by davetcoleman** [comment]
Confirmed, the problem appears fixed in the newest fuerte version. Thanks!
