### ISSUE TITLE
Suggestion: Rename roslaunch files used as includes to .launch.xml

### ISSUE THREAD

**Issue by bit-pirate** [moveit/moveit_setup_assistant#52]
This will hide those launchers from roslaunch's tab completion and thereby make it easier for the user to understand which launchers are intended to be used directly.

See https://github.com/ros/ros_comm/issues/254 for discussion details.

**Comment by bit-pirate** [comment]
Cool! Thanks!

**Comment by davetcoleman** [comment]
Nice!
