### ISSUE TITLE
Generate joint_limits.yaml using ordered joints

### ISSUE THREAD

**Issue by JeremyZoss** [moveit/moveit_setup_assistant#53]
The joint_limits.yaml file is currently generated using a seemingly random joint ordering.  This can lead to confusion, if users edit the file without checking the joint name field.  Most users probably expect the joints to be listed in a sensible ordering: base->tip, alphabetically, matching URDF ordering, etc.

It would be nice to impose some sort of ordering, to minimize confusion.

**Comment by felix-kolbe** [comment]
+1  This would also avoid pointless changes in version control

**Comment by davetcoleman** [comment]
Done, your welcome ;-)
