### ISSUE TITLE
Clarify UI for creating planning groups

### ISSUE THREAD

**Issue by hersh** [moveit/moveit_setup_assistant#59]
When creating a planning group, there are 4 buttons, one of which says it is "recommended" and the others say they are optional.  What is not clear is that you should do one of them, but not all of them.

Coming to this without reading the tutorial, I thought I needed to enter all the joints, all the links, and the chain.  Actually any one of those should be fine.  However in my experience, only the "chain" version actually worked.  That is a separate bug though, probably in some core moveit library.

**Comment by davetcoleman** [comment]
We thought about and have modified this screen a lot to make it more obvious, but I think these concepts are something you just need to read documentation to understand. Please post a recommended change if you have issue with it.

Note also that you can in fact do a combination of them if you want, though this is not the typical usage model. Usually its choose one.

**Comment by isucan** [comment]
+1 i find this quite confusing as well. Not sure how to best handle it though...

**Comment by hersh** [comment]
I think a big thing for making it more clear would be to provide visible feedback about the current state.  If someone specifies a chain, we can show the list of link/joint/link/joint/link that has been derived.  If they specify a bunch of joints instead, again show the list of link/joint/link etc that is derived.  Same for links.  This way the redundancy of specifying links _and_ joints becomes clear.

If you show people the output that their input causes right away, you don't need to be so careful to explain it because they can just fiddle with it until the output looks right.

**Comment by hersh** [comment]
Though I suppose it is a bit confusing that the inputs to that GUI are just an echo of what goes into the SRDF file.  The list of link/joint/link/etc must be derived from the "chain" specification (for instance) by whatever reads the SRDF.

**Comment by mikeferguson** [comment]
ported to consolidated repo
