### ISSUE TITLE
Unable to parse joint value ('a,bb') for joint 'xxx' in group state 'yyy'

### ISSUE THREAD

**Issue by HWiese1980** [moveit/moveit_setup_assistant#69]
There's a comma in the produced joint value in the resulting SRDF where instead a point should be. Thus the MoveIt stack isn't able to parse the value (or at least says so).

After manually changing the comma to a point the error message is gone and everything's working as expected.

The system's language I'm running ROS on is set to German. I suppose this issue is related to the language setting. 

![urdf_2](https://f.cloud.github.com/assets/743912/1851106/ccbb72a8-76e2-11e3-84e1-9189407d29e3.png)

**Comment by filipjares** [comment]
Hi, there is already an issue for that: https://github.com/ros-planning/moveit_setup_assistant/issues/51.

**Comment by HWiese1980** [comment]
Alright, thanks!
