### ISSUE TITLE
Generated file planning_context.launch includes absolute path

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_setup_assistant#7]
The planning_context.launch file is generated with an absolute path inside:

 
  <param if="$(arg load_robot_description)" name="robot_description" textfile="<absolute_path>" />

Should include the corresponding $(find <package>) instead

**Comment by isucan** [comment]
If the URDF file you loaded in the assistant was not in your ROS path and a package.xml was not found to identify a package, then an absolute path should be used. Was this absolute path generated for an XML file that was indeed in a package?

**Comment by marioprats** [comment]
All right. It was a package in my ROS_PACKAGE_PATH, but not catkinized, and therefore without the package.xml
