### ISSUE TITLE
Support for yaml-cpp 0.5+

### ISSUE THREAD

**Issue by bchretien** [moveit/moveit_setup_assistant#70]
Currently, compilation fails with yaml-cpp >= 0.5 (Fedora, Arch Linux, probably the incoming Ubuntu release as well etc.). This has been fixed in rviz and map_server (https://github.com/ros-planning/navigation/pull/140), but not yet in moveit_setup_assistant apparently.

**Comment by hersh** [comment]
I'm looking into this.
