### ISSUE TITLE
move_setup_assistant crash during URDF Load - Ogre Assertion

### ISSUE THREAD

**Issue by stephanbehm** [moveit/moveit_setup_assistant#74]
Hi everyone,

we are currently implementing a 6DoF-arm (Schäubli RX60B/RX60BL/RX90b).

Everything works fine, as long as Joint 6 is fixed, but it should be continuous to use all 6dof. 

Error-Msg: http://pastebin.com/aKKatdTD

URDF-error: http://pastebin.com/SYZsutT0

URDF-working: http://pastebin.com/jXWxPn26

The only difference is the type of "joint 6", which is fixed or continuous.
###### 

moveit_setup_assistant: /build/buildd/ogre-1.7.4/OgreMain/src/OgreNode.cpp:393: virtual void Ogre::Node::setOrientation(const Ogre::Quaternion&): Assertion `!q.isNaN() && "Invalid orientation supplied as parameter"' failed
###### 

OS: Ubuntu 12.04 LTS (64bit)
ROS: Hydro

Could there be a problem with the .STL-files? 

Best regards,
Stephan

**Comment by hersh** [comment]
The axis of rotation of joint 6 is 0,0,0.  It should be a unit vector.

You can update the bug if you like with a request to emit a more useful error message. :)
