### ISSUE TITLE
add option to specify number of IK attempts

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_setup_assistant#8]

**Comment by davetcoleman** [comment]
can it be any integer?

**Comment by isucan** [comment]
well, it should be >= 1, but <= reasonable; what reasonable is... I am not sure. 10? 1000? 1 mil ? :) I'd probably would not set an upper limit.

**Comment by davetcoleman** [comment]
i have set the yaml file to call it 'kinematics_solver_attempts' 
https://github.com/ros-planning/moveit_setup_assistant/commit/8b7a517307c59f512af6d2ea261de76905d4f690

**Comment by davetcoleman** [comment]
And https://github.com/ros-planning/moveit_setup_assistant/commit/f7c33b6bd3519d86f483c56f727991c77c6795b1
