### ISSUE TITLE
Setup Assistant vertical size too big

### ISSUE THREAD

**Issue by Samsagax** [moveit/moveit_setup_assistant#82]
The current Moveit setup assistant is too tall for screens resolutions 768px tall or less.

The problem is the window is not resizable and it's useless in a laptop with 1366x768 resolutions.

Here is a pic:

![captura de pantalla de 2014-03-13 15 00 11](https://f.cloud.github.com/assets/798775/2413049/bd2d1de8-aad9-11e3-9a66-a28b57efd68a.png)

The lower buttons are unreachable.

**Comment by ktiwari9** [comment]
I have the same problem. Any suggestions on how to solve this ?

**Comment by hersh** [comment]
What version are you using?  My fix for this was supposed to have been released in 0.5.9.

My fix was to use 700 pixels as the minimum height.  What's the vertical resolution of your screen?

For  a proper fix, the layout of the GUI elements on the intro screen needs to be changed.  That's a bigger job than I have time for right now, but if you want to work on it, I'll be happy to look it over.

**Comment by LeonhardEuler** [comment]
I've found a workaround. If you can't change you vertical resolution and you have multiple desktop workspaces, you can access the buttons by moving the assistant window halfway to one of the workspaces in the top row and switching to a lower workspace.

**Comment by davetcoleman** [comment]
I just checked the `hydro-devel` source code version and it is currently 732 pixels using @hersh's fix. Please confirm you are still experiencing this issue in debian version 0.5.9 otherwise I'd like to close this.
