### ISSUE TITLE
OMPL parameter syntax should be in default ompl_planning.yaml

### ISSUE THREAD

**Issue by drchrislewis** [moveit/moveit_setup_assistant#84]
Each OMPL planner plug-in declares a small set of parameters. It is not obvious what parameters are available, the syntax for changing them, nor what they do. I would like to add this minimal information as comments to the default ompl_planning.yaml file which is created by the setup assistant.

**Comment by davetcoleman** [comment]
+1 This would be great, please do!

**Comment by davetcoleman** [comment]
Addressed in https://github.com/ros-planning/moveit_setup_assistant/pull/85
