### ISSUE TITLE
Add command-line scripting support

### ISSUE THREAD

**Issue by JeremyZoss** [moveit/moveit_setup_assistant#87]
We are interested in automating the (already easy to use) Setup Assistant to automatically fill in the fields with standard / nominal values.

The concept is that we would run a python script against a user-provided URDF to determine the appropriate input values to the Setup Assistant.  Ideally, we could then generate some sort of config file and feed that as input to the Setup Assistant to automatically generate the package configuration/launch files with no additional user input.  Clearly, this auto-generation script would only work for relatively standard/simple robots and URDF setups.

We could probably use the existing SRDF format for this input config file, but it doesn't capture the necessary inputs for, e.g. building the allowed-collision matrix.

This is definitely a "nice to have" (not a bug), but would help streamline the process of setting up a new robot or workcell.

**Comment by davetcoleman** [comment]
Does it have to be python? The SA is in C++. I think this functionality could go inside of the SA as a command line alternative.

**Comment by JeremyZoss** [comment]
Agreed.  My intent was not to add a python-native interface to SA, but to provide appropriate command-line options to the existing C++ SA that would allow us to call it from our python scripts like any other system executable.  The python part was for context, not intended as an implementation requirement.  =)

**Comment by davetcoleman** [comment]
Any progress in this? Is interest lost?

**Comment by JeremyZoss** [comment]
I’m still interested, but haven’t had time to work on it yet.  I probably won’t in the near future, either.  I’d prefer to leave the enhancement request open, for tracking, if possible.

**Comment by mikeferguson** [comment]
added to ticket in new consolidated repo
