### ISSUE TITLE
Indigo-devel branches

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_setup_assistant#97]
Just a heads up that I have branched for indigo to add new settings only availble in that release.

@isucan when you release an updated moveit_setup_assistant, can you edit the indigo config to point to the new branch? Or should I just release an update now myself?

**Comment by isucan** [comment]
If you have a chance Dave, please release yourself. Thanks!

**Comment by davetcoleman** [comment]
Actually, I shouldn't release the indigo branch until moveit_ros is also released, otherwise there will be a missing octomap_service in user's launch files.

**Comment by davetcoleman** [comment]
I've just realeased it:
https://github.com/ros/rosdistro/pull/6386
